clinic-info:
  name: 'my clinic'
  working-hours: '8-17'

spring:
  datasource:
    url:
    username: postgres
    password: postgres
  jackson.property-naming-strategy: SNAKE_CASE
  jpa.show-sql: true

logging.level.org.hibernate: DEBUG