clinic-info:
  name: 'my clinic'
  working-hours: '8-17'

spring:
  datasource:
    url: jdbc:postgresql:postgres
    username: postgres
    password: postgres
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      write-dates-as-timestamps: false
      indent-output: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: create
    open-in-view: false

#logging.level.org.hibernate: DEBUG